# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66de94744a51592e418ca8f3b150103f0af48e14c0254610c6c08ce19276df70dee54dbf993586690f8262b9c8ebb0c69694d2ea1ca7f6ba8c10e5dead61fd74

test:
  secret_key_base: 53f869f25f90951171cca3b1ad8f40a66c19a22c985c6693217ae2ef6e36c601ea87312d02aec1fd8ea8b66f40e52738bf3578c10d0ebc64a59ba7db879ecc49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
